goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product')
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from myproject import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('catalog/', include('goods.urls', namespace='catalog')),
                  path('user/', include('users.urls', namespace='user'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='name')
    slug = models.SlugField(max_length=150, unique=True, verbose_name='slug')

    class Meta:
        db_table = 'category'
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=120, unique=True, verbose_name='name')
    slug = models.SlugField(max_length=120, unique=True, verbose_name='slug')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='price')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='category')
    image = models.ImageField(upload_to="goods/", verbose_name='image', blank=True, null=True)
    description = models.TextField(verbose_name='description')
    discount = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    on_stock = models.BooleanField(default=False, verbose_name='on stock')

    class Meta:
        db_table = 'product'
        verbose_name = 'product'
        verbose_name_plural = "products"
        ordering = ('id',)

    def __str__(self):
        return f'{self.name} pricee- {self.price}'

    def display_id(self):
        return f'{self.id:05} '

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)

        return self.price

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_list_or_404

from goods.models import Product
from goods.utils import q_search


# Create your views here.
def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if category_slug == 'all':
        goods = Product.objects.all()
    elif query:
        goods = q_search(query)

    else:
        goods = get_list_or_404(Product.objects.filter(category__slug=category_slug))

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != 'default':
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))

    context = {
        'title': 'home/catalog',
        'goods': current_page,
        'slug_url': category_slug,
    }
    return render(request, 'goods/catalog.html', context)


def product(request, product_slug):
    products = Product.objects.get(slug=product_slug)
    context = {
        'title': 'home/catalog/product',
        'product': products
    }
    return render(request, 'goods/products.html', context)

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% load goods_tags %}

    <!-- Контент на странице -->
    <div class="row">
        <!-- Форма фильтров -->
        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                Filters
            </button>

            <form action="
                    {% if request.GET.q %}{% url 'catalog:search' %}{% else %}{% url "catalog:index" slug_url %}{% endif %}"
                  method="get" class="dropdown-menu bg-dark"
                  data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
                    >
                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{ request.GET.q }}">
                    {% endif %}
                    <label class="form-check-label" for="flexCheckDefault">
                        Товары по акции
                    </label>
                </div>
                <p class="text-white mx-3 mt-3">Сортировать:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                            {% if not request.GET.order_by or request.GET.order_by == 'default' %} checked {% endif %} >
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                            {% if request.GET.order_by == 'price' %} checked {% endif %} >
                    <label class="form-check-label" for="flexRadioDefault2">
                        От дешевых к дорогим
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                            {% if request.GET.order_by == '-price' %} checked {% endif %} >
                    <label class="form-check-label" for="flexRadioDefault3">
                        От дорогих к дешевым
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>
        <!-- Карта товара -->

    {% if request.GET.q %}
    	<h3 class="m-4">The result of query {{ request.GET.q }}</h3>
    {% endif %}
    {% if not goods %}
        <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
        <h3 class="m-4">Not found</h3>
    {% endif %}

        {% for product in goods %}
            <div class="col-lg-4 col-md-6 p-4">
                <div class="card border-primary rounded custom-shadow">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}"
                             style="height: 200px;">
                    {% else %}
                        <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top"
                             alt="{{ product.name }}" style="height: 200px;">
                    {% endif %}
                    <div class="card-body">
                        <a href="{% url "catalog:product" product.slug %}">
                            <p class="card-title">
                            {% autoescape off %}
                                {% if product.headline %}
                                {{ product.headline }}
                                {% else %}
                                {{ product.name }}
                                {% endif %}
                            {% endautoescape %}
                            </p>
                        </a>
                        <p class="card-text ">
                             {% autoescape off %}
                                {% if product.bodyline %}
                                {{ product.bodyline|truncatechars:100 }}
                                {% else %}
                                {{ product.description|truncatechars:35 }}
                                {% endif %}
                            {% endautoescape %}
                            </p>
                        <p class="product_id">id: {{ product.display_id }}</p>
                        <div class="d-flex justify-content-between">
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s> $</p>
                                <p><strong>{{ product.sell_price }} $</strong></p>
                                <span class="badge bg-warning text-dark">Discount {{ product.discount }} %</span>

                            {% else %}
                                <p><strong>{{ product.price }} $</strong></p>
                            {% endif %}
                            <a href="#" class="btn">
                                <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                     width="32" height="32">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <!-- Пагинация -->
    {% if goods %}
    	<nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">
                <li class="page-item {% if not goods.has_previous %}disabled {% endif %} ">
                    <a class="page-link"
                       href="{% if goods.has_previous %}?{% change_params page=goods.previous_page_number %}{% else %}# {% endif %}">Previous</a></li>
                {% for page in  goods.paginator.page_range %}
                    {% if page >= goods.number|add:-2 and page <= goods.number|add:+2 %}
                        <li class="page-item {% if goods.number == page %}active{% endif %}">
                            <a class="page-link" href="?{% change_params page=page %}">{{ page }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item {% if not goods.has_next %}disabled {% endif %} ">
                    <a class="page-link"
                       href="{% if goods.has_next %}?{% change_params page=goods.next_page_number %}{% else %}#{% endif %}">Next</a></li>
            </div>
        </ul>
    </nav>
    {% endif %}
{% endblock %}
{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <div class="dh9">
                <div class="d9h text-black-50">
                    <span class="hd9">О Нас</span>
                    <a class="nav-link text-white" title="О Нас" target="_blank" href="{% url "main:about" %}"
                       class="a1l h9d">О Нас</a>
                    <a title="контактная информация" href="#" class="nav-link text-white">Контактная информация</a>
                    <a title="Партнерство" href="#" class="nav-link text-white">Парптнерство с нами</a>
                </div>
                <div class="d9h text-white"><span class="hd9">Наши соц-сети</span>
                    <a class="nav-link text-white" href="#"><i class="fa-brands fa-instagram"></i> instagram</a>
                    <a class="nav-link text-white" href="#"><i class="fa-brands fa-telegram"></i> telegram</a>
                    <a href="#" class="nav-link text-white"><i class="fa-brands fa-whatsapp"></i> whatsapp</a>
                </div>
            </div>
            <p class="m-0 text-center text-white">Copyright &copy; Food-corp 2024</p>
        </div>
    </footer>
{% endblock %}

goods/templates/goods/products.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    <img src="{{ product.image.url }}"
                         class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                </div>
                <div class="col-md-4 ">
                    <p class="product_id mt-3">id:{{ product.display_id }}</p>
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                     aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ product.image.url }}"
                                     class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <p class="card-text">Цена: <strong>{{ product.sell_price }} $</strong></p>
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
            </div>
        </div>
    </div>
{% endblock %}